config/routes.rb
Lesite::Application.routes.draw do
  root :to => "posts#index"

  resources :inscrits

  resources :posts, :interviews, :articles, :emissions do
    resources :commentaires
  end

  devise_for :users
  match 'users', :to => "users#index"
  match 'users/poles', :to => "users#poles", :as => :poles

end

app/models/inscrit.rb
class Inscrit < ActiveRecord::Base
  attr_accessible :name, :email

  validates_presence_of :name, :email
end

app/controllers/inscrits_controller.rb
class InscritsController < ApplicationController
  # GET /inscrits
  # GET /inscrits.json
  def index
    @inscrits = Inscrit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @inscrits }
    end
  end

  # GET /inscrits/1
  # GET /inscrits/1.json
  def show
    @inscrit = Inscrit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @inscrit }
    end
  end

  # GET /inscrits/new
  # GET /inscrits/new.json
  def new
    @inscrit = Inscrit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @inscrit }
    end
  end

  # GET /inscrits/1/edit
  def edit
    @inscrit = Inscrit.find(params[:id])
  end

  # POST /inscrits
  # POST /inscrits.json
  def create
    @inscrit = Inscrit.new(params[:inscrit])

    respond_to do |format|
      if @inscrit.save
        format.html { redirect_to @inscrit, :notice => 'Inscrit was successfully created.' }
        format.json { render :json => @inscrit, :status => :created, :location => @inscrit }
      else
        format.html { render :action => "new" }
        format.json { render :json => @inscrit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /inscrits/1
  # PUT /inscrits/1.json
  def update
    @inscrit = Inscrit.find(params[:id])

    respond_to do |format|
      if @inscrit.update_attributes(params[:inscrit])
        format.html { redirect_to @inscrit, :notice => 'Inscrit was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @inscrit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /inscrits/1
  # DELETE /inscrits/1.json
  def destroy
    @inscrit = Inscrit.find(params[:id])
    @inscrit.destroy

    respond_to do |format|
      format.html { redirect_to inscrits_url }
      format.json { head :ok }
    end
  end
end

app/helpers/inscrits_helper.rb
module InscritsHelper
end

app/views/inscrits/_form.html.erb
<%= form_for(Inscrit.new) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inscrits/edit.html.erb
<h1>Editing inscrit</h1>

<%= render 'form' %>

<%= link_to 'Show', @inscrit %> |
<%= link_to 'Back', inscrits_path %>

app/views/inscrits/index.html.erb
<h1>Listing inscrits</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inscrits.each do |inscrit| %>
  <tr>
    <td><%= inscrit.name %></td>
    <td><%= inscrit.email %></td>
    <td><%= link_to 'Show', inscrit %></td>
    <td><%= link_to 'Edit', edit_inscrit_path(inscrit) %></td>
    <td><%= link_to 'Destroy', inscrit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inscrit', new_inscrit_path %>

app/views/inscrits/new.html.erb
<h1>New inscrit</h1>

<%= render 'form' %>

<%= link_to 'Back', inscrits_path %>

app/views/inscrits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @inscrit.name %>
</p>

<p>
  <b>Email:</b>
  <%= @inscrit.email %>
</p>


<%= link_to 'Edit', edit_inscrit_path(@inscrit) %> |
<%= link_to 'Back', inscrits_path %>